Revert "get integers / mpi refactor"
This reverts commit c3dde74b2fcdb0e5b2ad4a6ddaa5ebfd2d3987c9.

This change looked good on the surface, but:
1. broke the unit tests
2. does not properly respect lists:
   TypeError: 'list' does not support the buffer interface

Revert it, and a later revision will reimplement a valid get_mpi
function that works in both Python 2 and 3.

Signed-off-by: Dan McGee <dpmcgee@gmail.com>